[build]  
  publish = "public"  
  functions = "netlify/functions"  
  command = "cd netlify/functions && npm install && cd ../../ && npm run test"  

[functions]  
  node_bundler = "esbuild"  

[context.production]  
  environment = {  
    INFLUX_URL = "https://us-east-1-1.aws.cloud2.influxdata.com",  
    INFLUX_TOKEN = "@influxdb_token",  
    INFLUX_ORG = "university_research",  
    ADMIN_TOKEN = "@admin_purge_token"  
  }  
