[build]
  publish = "public"
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install && cd ../../ && npm run test"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  INFLUX_URL = "your_influx_url_here"
  INFLUX_TOKEN = "your_influx_token_here"
  INFLUX_ORG = "your_influx_org_here"
  ADMIN_TOKEN = "your_admin_purge_token_here"
