[build]  
  publish = "public"  
  functions = "netlify/functions"  
  command = "npm install && echo 'Dependencies installed'"  

[functions]  
  node_bundler = "esbuild"  
[build]  
  command = "npm install && node test/deploy-verification.js"  
