[build]  
  publish = "public"  
  functions = "netlify/functions"  
  command = "cd netlify/functions && npm install && cd ../../ && npm run test"  
  node_bundler = "esbuild"  # <-- MOVED INSIDE [build]  

[build.environment]  
  NODE_VERSION = "18"  

[context.production.environment]  
  INFLUX_URL = "your_influx_url"  
  INFLUX_TOKEN = "your_influx_token"  
  INFLUX_ORG = "your_influx_org"  
  ADMIN_TOKEN = "your_admin_token"  
